### ISSUE TITLE
SSL error when connecting

### ISSUE THREAD

**Issue by danieljoly** [erijo/tellive-py#6]
Trying tellive-py for the first time, (want to log sensor data), and my python skills are lacking. Getting this error when trying to connect using the tellive_core_connector script:

```
2015-10-30 15:42:54,187 ERROR: Communication error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)
```

Also tried connecting using your API example, resulting in the same error:

```
(server, port) = client.connect_to_first_available_server()
Traceback (most recent call last):
  File "<pyshell#22>", line 1, in <module>
    (server, port) = client.connect_to_first_available_server()
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\tellive\tellstick.py", line 96, in connect_to_first_available_server
    for server in self.servers():
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\tellive\tellstick.py", line 64, in servers
    conn.request('GET', "/server/assign?protocolVersion=2")
  File "C:\Program Files (x86)\Python 3.5\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "C:\Program Files (x86)\Python 3.5\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Program Files (x86)\Python 3.5\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "C:\Program Files (x86)\Python 3.5\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python 3.5\lib\http\client.py", line 854, in send
    self.connect()
  File "C:\Program Files (x86)\Python 3.5\lib\http\client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python 3.5\lib\ssl.py", line 376, in wrap_socket
    _context=self)
  File "C:\Program Files (x86)\Python 3.5\lib\ssl.py", line 747, in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Python 3.5\lib\ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files (x86)\Python 3.5\lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)
```

-Daniel

**Comment by erijo** [comment]
Please test with the latest master and let me know if that works better for you.

**Comment by erijo** [comment]
Assuming fixed.
